import { ArrowUpRight } from 'lucide-react'
import { motion, useReducedMotion } from 'framer-motion'
import type { Project } from '../../types/portfolio'
import { ProjectVisual } from './ProjectVisual'
import { TechnologyChip } from './TechnologyChip'

type FeaturedProjectCardProps = { project: Project; onSelect: (project: Project) => void }

export function FeaturedProjectCard({ project, onSelect }: FeaturedProjectCardProps) {
  const reduceMotion = useReducedMotion()
  return <article className="overflow-hidden rounded-2xl border border-[var(--color-border-strong)] bg-[linear-gradient(135deg,rgba(124,140,255,0.09),rgba(255,255,255,0.015)_48%,rgba(255,255,255,0.03))] shadow-[var(--shadow-glass)]"><div className="grid lg:grid-cols-[minmax(0,0.93fr)_minmax(24rem,0.85fr)]"><motion.div initial={reduceMotion ? false : { opacity: 0, scale: 0.97 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1] }} className="order-first lg:order-last"><ProjectVisual project={project} aspect="feature" /></motion.div><motion.div initial={reduceMotion ? false : { opacity: 0, x: -18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.55, delay: reduceMotion ? 0 : 0.12, ease: [0.22, 1, 0.36, 1] }} className="flex flex-col p-6 sm:p-8 lg:p-10"><div className="flex items-center justify-between gap-4"><span className="font-mono text-[0.68rem] font-medium uppercase tracking-[0.16em] text-[var(--color-accent)]">Featured / {project.category}</span><span className="rounded-full border border-[var(--color-border)] px-2.5 py-1 font-mono text-[0.62rem] uppercase tracking-[0.13em] text-[var(--color-text-muted)]">Project status / {project.status}</span></div><h3 className="mt-7 text-balance text-[clamp(2rem,4vw,3.3rem)] font-semibold leading-[0.98] tracking-[-0.055em] text-white">{project.title}</h3><p className="mt-5 max-w-xl text-pretty text-base leading-7 text-[var(--color-text-muted)]">{project.shortDescription}</p><motion.div initial={reduceMotion ? false : { opacity: 0, y: 8 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.4, delay: reduceMotion ? 0 : 0.32 }} className="mt-7 flex flex-wrap gap-2">{project.technologies.map((technology) => <TechnologyChip key={technology} technology={technology} />)}</motion.div><button type="button" onClick={() => onSelect(project)} className="mt-8 inline-flex w-fit items-center gap-2 rounded-lg bg-[var(--color-accent)] px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--color-accent-strong)]">View Project <ArrowUpRight size={17} aria-hidden="true" /></button></motion.div></div></article>
}
