import { motion, useReducedMotion } from 'framer-motion'
import type { Education } from '../../types/portfolio'

type EducationCardProps = { education: Education }

export function EducationCard({ education }: EducationCardProps) {
  const reduceMotion = useReducedMotion()
  return <motion.article initial={reduceMotion ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.5, delay: reduceMotion ? 0 : 0.16, ease: [0.22, 1, 0.36, 1] }} className="relative overflow-hidden rounded-2xl border border-[var(--color-border-strong)] bg-[linear-gradient(135deg,rgba(124,140,255,0.09),rgba(255,255,255,0.02)_55%,rgba(255,255,255,0.04))] p-6 shadow-[var(--shadow-glass)] sm:p-8"><div aria-hidden="true" className="absolute -right-16 -top-16 size-56 rounded-full bg-[var(--color-accent)]/10 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><p className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-[var(--color-accent)]">{education.current ? 'Current academic program' : 'Academic record'}</p><h3 className="mt-5 text-balance text-2xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-3xl">{education.degree}</h3><p className="mt-4 font-mono text-xs uppercase tracking-[0.12em] text-[var(--color-text-subtle)]">{education.duration}</p></div><div><p className="text-base font-medium text-white">{education.institution}</p><p className="mt-1 text-sm text-[var(--color-text-subtle)]">{education.location}</p><p className="mt-5 max-w-2xl text-sm leading-6 text-[var(--color-text-muted)] sm:text-base sm:leading-7">{education.description}</p>{education.details?.length ? <ul className="mt-5 grid gap-2 sm:grid-cols-2">{education.details.map((detail) => <li key={detail} className="rounded-lg border border-[var(--color-border)] bg-white/[0.02] px-3 py-2 text-sm text-[var(--color-text-muted)]">{detail}</li>)}</ul> : null}</div></div></motion.article>
}
